import Head from 'next/head';
import React from 'react';
import { LangHelper } from '../Helper/MultiLangHelper/LangHelper';

export default function Home() {
  return (
    <main>
      <Head>
        <title>{LangHelper("AppName")}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />
        Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />
        Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />
        Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />
        Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />
        Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />Home<br />
      </div>
    </main>
  )
}
